-- MASTER TABLE
CREATE TABLE PUBLIC.TENANT
(
    TENANT_ID    VARCHAR(255) NOT NULL
        PRIMARY KEY,
    NAME         VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY   VARCHAR(255),
    DELETED_DATE VARCHAR(255)
);

ALTER TABLE PUBLIC.TENANT
    OWNER TO POSTGRES;
INSERT INTO public.tenant (tenant_id, name, created_date, updated_date, updated_by, deleted_date) VALUES ('T00001', 'GRAND INDONESIA', '2025-07-07 10:23:42.000000', '2025-07-07 10:23:45.000000', 'SYSTEM', null);


CREATE TABLE PUBLIC.GATE_TENANT
(
    GATEID       VARCHAR NOT NULL
        PRIMARY KEY,
    TENANT_ID    VARCHAR
        REFERENCES PUBLIC.TENANT,
    GATETYPE     VARCHAR
        CONSTRAINT GATE_TENANT_GATETYPE_CHECK
            CHECK ((GATETYPE)::TEXT = ANY ((ARRAY ['IN'::CHARACTER VARYING, 'OUT'::CHARACTER VARYING])::TEXT[])),
    ALIAS        VARCHAR,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY   VARCHAR,
    DELETED_DATE TIMESTAMP
);
ALTER TABLE PUBLIC.GATE_TENANT
    OWNER TO POSTGRES;
INSERT INTO public.gate_tenant (gateid, tenant_id, gatetype, alias, created_date, updated_date, updated_by, deleted_date) VALUES ('G00001', 'T00001', 'IN', 'North Gate IN', '2025-07-07 10:27:26.000000', '2025-07-07 10:27:28.000000', 'SYSTEM', null);
INSERT INTO public.gate_tenant (gateid, tenant_id, gatetype, alias, created_date, updated_date, updated_by, deleted_date) VALUES ('G00002', 'T00001', 'OUT', 'South Gate OUT', '2025-07-07 10:28:00.000000', '2025-07-07 10:28:01.000000', 'SYSTEM', null);

CREATE TABLE PUBLIC.VEHICLE_TYPE
(
    VEHICLETYPE  VARCHAR NOT NULL
        PRIMARY KEY,
    NAME         VARCHAR,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY   VARCHAR,
    DELETED_DATE TIMESTAMP
);
ALTER TABLE PUBLIC.VEHICLE_TYPE
    OWNER TO POSTGRES;
INSERT INTO public.vehicle_type (vehicletype, name, created_date, updated_date, updated_by, deleted_date) VALUES ('MB', 'MOBIL', '2025-07-07 10:21:59.000000', '2025-07-07 10:22:05.000000', 'SYSTEM', null);
INSERT INTO public.vehicle_type (vehicletype, name, created_date, updated_date, updated_by, deleted_date) VALUES ('MT', 'MOTOR', '2025-07-07 10:22:17.000000', '2025-07-07 10:22:19.000000', 'SYSTEM', null);


CREATE TABLE PUBLIC.VEHICLE
(
    VEHICLENUM   VARCHAR NOT NULL
        PRIMARY KEY,
    VEHICLETYPE  VARCHAR
        REFERENCES PUBLIC.VEHICLE_TYPE,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY   VARCHAR,
    DELETED_DATE TIMESTAMP
);

ALTER TABLE PUBLIC.VEHICLE
    OWNER TO POSTGRES;
INSERT INTO public.vehicle (vehiclenum, vehicletype, created_date, updated_date, updated_by, deleted_date) VALUES ('B3333MT', 'MT', '2025-07-07 10:30:24.000000', '2025-07-07 10:30:26.000000', 'SYSTEM', null);
INSERT INTO public.vehicle (vehiclenum, vehicletype, created_date, updated_date, updated_by, deleted_date) VALUES ('B1234MB', 'MB', '2025-07-07 10:19:38.000000', '2025-07-07 10:19:41.000000', 'SYSTEM', null);


CREATE TABLE PUBLIC.MEMBER
(
    MEMBERID     VARCHAR NOT NULL
        PRIMARY KEY,
    NAME         VARCHAR,
    EMAIL        VARCHAR,
    PHONENUMBER  VARCHAR,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY   VARCHAR,
    DELETED_DATE TIMESTAMP
);

ALTER TABLE PUBLIC.MEMBER
    OWNER TO POSTGRES;

CREATE TABLE PUBLIC.VEHICLE_MEMBER
(
    VEHICLENUM   VARCHAR NOT NULL
        REFERENCES PUBLIC.VEHICLE,
    MEMBERID     VARCHAR NOT NULL
        REFERENCES PUBLIC.MEMBER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY   VARCHAR,
    DELETED_DATE TIMESTAMP,
    PRIMARY KEY (VEHICLENUM, MEMBERID)
);

ALTER TABLE PUBLIC.VEHICLE_MEMBER
    OWNER TO POSTGRES;

CREATE TABLE PUBLIC.USER_TENANT
(
    UUID         UUID NOT NULL
        PRIMARY KEY,
    USERNAME     VARCHAR,
    PASSWORD     VARCHAR,
    EMAIL        VARCHAR,
    TENANT_ID    VARCHAR
        REFERENCES PUBLIC.TENANT,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY   VARCHAR,
    DELETED_DATE TIMESTAMP
);

ALTER TABLE PUBLIC.USER_TENANT
    OWNER TO POSTGRES;
INSERT INTO public.user_tenant (uuid, username, password, email, tenant_id, created_date, updated_date, updated_by, deleted_date) VALUES ('9c13b145-993f-4dcb-9403-c9ed7b264aa1', 'user', '5f4dcc3b5aa765d61d8327deb882cf99', 'admingi@gmail.com', 'T00001', '2025-07-07 10:25:36.000000', '2025-07-07 10:25:38.000000', null, null);


CREATE TABLE PUBLIC.PAYMENTTYPE
(
    PAYMENTTYPEID VARCHAR NOT NULL
        PRIMARY KEY,
    NAME          VARCHAR,
    CREATED_DATE  TIMESTAMP,
    UPDATED_DATE  TIMESTAMP,
    UPDATED_BY    VARCHAR
);

ALTER TABLE PUBLIC.PAYMENTTYPE
    OWNER TO POSTGRES;
INSERT INTO public.paymenttype (paymenttypeid, name, created_date, updated_date, updated_by) VALUES ('P001', 'CASH', '2025-07-09 14:08:59.000000', null, 'SYSTEM');



-- TRANSACTION TABLE
CREATE TABLE PUBLIC.TRANSACTION
(
    TRANSACTIONID UUID NOT NULL
        PRIMARY KEY,
    AMOUNT        NUMERIC(10, 2),
    PAYMENTTYPEID VARCHAR
        CONSTRAINT TRANSACTION_PAYMENTTYPEID_FK
            REFERENCES PUBLIC.PAYMENTTYPE,
    ISPAID        BOOLEAN,
    MEMBERID      VARCHAR
        REFERENCES PUBLIC.MEMBER,
    DURATION      BIGINT,
    RATE          NUMERIC(10, 2),
    REFID         VARCHAR,
    UPDATED_DATE  TIMESTAMP
);


ALTER TABLE PUBLIC.TRANSACTION
    OWNER TO POSTGRES;

CREATE TABLE PUBLIC.TICKET
(
    NOTICKET      UUID NOT NULL
        PRIMARY KEY,
    VEHICLENUM    VARCHAR
        REFERENCES PUBLIC.VEHICLE,
    INDATE        TIMESTAMP,
    OUTDATE       TIMESTAMP,
    GATEIN        VARCHAR
        REFERENCES PUBLIC.GATE_TENANT,
    GATEOUT       VARCHAR
        REFERENCES PUBLIC.GATE_TENANT,
    TRANSACTIONID UUID
        CONSTRAINT TICKET_TRANSACTIONID_FK
            REFERENCES PUBLIC.TRANSACTION,
    TENANT_ID     VARCHAR
        CONSTRAINT TICKET_TENANTID_FK
            REFERENCES PUBLIC.TENANT,
    OUTDATE_SCAN  TIMESTAMP
);

ALTER TABLE PUBLIC.TICKET
    OWNER TO POSTGRES;

