Link Figjam : https://www.figma.com/board/3okuQac4o8yE67VbDbJmoB/ParkingPos_designERD?node-id=0-1&t=v9LI2pIMk5zsdfMX-1


-- =====================
-- MASTER TABLES
-- =====================

CREATE TABLE TENANT (
    TENANT_ID VARCHAR PRIMARY KEY,
    NAME VARCHAR,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR,
    DELETED_DATE TIMESTAMP
);

CREATE TABLE USER_TENANT (
    UUID UUID PRIMARY KEY,
    USERNAME VARCHAR,
    PASSWORD VARCHAR,
    EMAIL VARCHAR,
    TENANT_ID VARCHAR REFERENCES TENANT(TENANT_ID),
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR,
    DELETED_DATE TIMESTAMP
);

CREATE TABLE GATE_TENANT (
    GATEID VARCHAR PRIMARY KEY,
    TENANT_ID VARCHAR REFERENCES TENANT(TENANT_ID),
    GATETYPE VARCHAR CHECK (GATETYPE IN ('IN', 'OUT')),
    ALIAS VARCHAR,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR,
    DELETED_DATE TIMESTAMP
);

CREATE TABLE VEHICLE_TYPE (
    VEHICLETYPE VARCHAR PRIMARY KEY,
    NAME VARCHAR,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR,
    DELETED_DATE TIMESTAMP
);

CREATE TABLE VEHICLE (
    VEHICLENUM VARCHAR PRIMARY KEY,
    VEHICLETYPE VARCHAR REFERENCES VEHICLE_TYPE(VEHICLETYPE),
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR,
    DELETED_DATE TIMESTAMP
);

CREATE TABLE MEMBER (
    MEMBERID VARCHAR PRIMARY KEY,
    NAME VARCHAR,
    EMAIL VARCHAR,
    PHONENUMBER VARCHAR,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR,
    DELETED_DATE TIMESTAMP
);

CREATE TABLE VEHICLE_MEMBER (
    VEHICLENUM VARCHAR REFERENCES VEHICLE(VEHICLENUM),
    MEMBERID VARCHAR REFERENCES MEMBER(MEMBERID),
    PRIMARY KEY (VEHICLENUM, MEMBERID),
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR,
    DELETED_DATE TIMESTAMP
);

-- =====================
-- TRANSACTIONAL TABLES
-- =====================
CREATE TABLE TRANSACTION (
    TRANSACTIONID VARCHAR PRIMARY KEY,
    AMOUNT DECIMAL,
    PAYMENTTYPE VARCHAR,
    CREATED_DATE TIMESTAMP,
    OUTDATE TIMESTAMP,
    ISPAID BOOLEAN,
    MEMBERID VARCHAR REFERENCES MEMBER(MEMBERID),
    DURATION INT,
    RATE INT,
    REFID VARCHAR,
    UPDATED_DATE TIMESTAMP
);

CREATE TABLE TICKET (
    NOTICKET VARCHAR PRIMARY KEY,
    VEHICLENUM VARCHAR REFERENCES VEHICLE(VEHICLENUM),
    VEHICLETYPE VARCHAR REFERENCES VEHICLE_TYPE(VEHICLETYPE),
    INDATE TIMESTAMP,
    OUTDATE TIMESTAMP,
    GATEIN VARCHAR REFERENCES GATE_TENANT(GATEID),
    GATEOUT VARCHAR REFERENCES GATE_TENANT(GATEID),
    TRANSACTIONID VARCHAR REFERENCES TRANSACTION(TRANSACTIONID)
);


